[tool.poetry]
name = "glcli"
version = "0.1.4"
description = ""
authors = ["Christian Decker <decker.christian@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8"
gl-client-py = "^0.1"

[tool.poetry.dev-dependencies]
gl-client-py = { path = "../../libs/gl-client-py/", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
glcli = 'glcli.cli:cli'

[[tool.poetry.source]]
name = "greenlight"
url = "https://us-west2-python.pkg.dev/c-lightning/greenlight-pypi/simple/"
