site_name: Greenlight Documentation
docs_dir: src
plugins:
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
theme:
  name: material
  palette:
    primary: blue grey
    scheme: default
    accent: indigo
  features:
    - navigation.tabs
nav:
  - Home:
    - index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Registering a node: getting-started/register.md
    - Starting a node: getting-started/schedule.md
    - Recover access: getting-started/recover.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Testing your app: tutorials/testing.md
    - Self-Hosting: tutorials/self-hosting.md
    - Standalone signer: tutorials/standalone-signer.md
  - Reference:
    - Overview: reference/index.md
    - Security: reference/security.md
    - Node RPC Proxy: reference/node-rpc-proxy.md
  - about.md
