site_name: Greenlight Documentation
docs_dir: src
plugins:
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
nav:
  - Home:
    - index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Registering a node: getting-started/register.md
    - Starting a node: getting-started/schedule.md
    - Recover access: getting-started/recover.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Testing your app: tutorials/testing.md
    - Self-Hosting: tutorials/self-hosting.md
    - Standalone signer: tutorials/standalone-signer.md
  - Reference:
    - Overview: reference/index.md
    - Security: reference/security.md
    - Node RPC Proxy: reference/node-rpc-proxy.md
    - reference/partner-certs.md
  - about.md
