name: Python

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - x86_64
          - i686
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    
    - uses: Swatinem/rust-cache@v2

    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist
        working-directory: libs/gl-client-py
        docker-options: -v /opt/hostedtoolcache/protoc/v23.2/x64/bin/protoc:/usr/bin/protoc:ro
      env:
        PROTOC: /opt/hostedtoolcache/protoc
  
    - name: Install built wheel
      if: matrix.target == 'x86_64'
      run: |
        pip install libs/gl-client-py/dist/gl_client*.whl --force-reinstall
        python -c "import glclient;tls=glclient.TlsConfig();signer=glclient.Signer(b'\x00'*32,'bitcoin', tls);print(repr(tls));print(signer.version())"

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: libs/gl-client-py/dist/


  linux-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64, armv7, s390x, ppc64le, ppc64]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        rust-toolchain: nightly
        target: ${{ matrix.target }}
        manylinux: auto
        args: --release --out dist
        docker-options: -v /opt/hostedtoolcache/protoc/v23.2/x64/bin/protoc:/usr/bin/protoc:ro

    - uses: uraimo/run-on-arch-action@v2.5.0
      if: matrix.target != 'ppc64'
      name: Install built wheel
      with:
        arch: ${{ matrix.target }}
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        install: |
          apt-get update
          apt-get install -y --no-install-recommends python3 python3-pip
          pip3 install -U pip pytest
        run: |
          pip3 install rjmespath --no-index --find-links dist/ --force-reinstall
          cd tests && pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: libs/gl-client-py/dist/